### ISSUE TITLE
request: looser syntax for powers

### ISSUE THREAD

**Issue by Konfekt** [arecarn/vim-crunch#57]
Instead of `pow(2,3)`, could `vim-crunch` accept also the more common, and intuitive, expressions `2^3` or `2**3` to compute the cube of `2`?

**Comment by arecarn** [comment]
I'd like that too. I think this would need a real parser, and right now crunch is just a bunch of search and replace hacks.  I'd like to do this one day but right now it's not a priority of mine.

**Comment by Konfekt** [comment]
That's great news
