### ISSUE TITLE
Could we set an option for allowing the users to remap the keybindings?

### ISSUE THREAD

**Issue by blasco** [arecarn/vim-crunch#63]
Current bindings are enforced. Is there a way to remap them? I use `g=` for other purposes, I would like to remap it go `gc` (go compute/crunch). Is it possible to customize this?

**Comment by arecarn** [comment]
I should document it but you can remap the bindings. Here's an example of your case.  You can put this in your vimrc, and the default bindings shouldn't be set.
    
    nmap gc <Plug>(crunch-operator)
    nmap gcc <Plug>(crunch-operator-line)
    xmap gc <Plug>(visual-crunch-operator)

**Comment by blasco** [comment]
Oh, great. Thank you very much
